app = "kino-backend"
primary_region = "ams"

[build]

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.checks]]
    grace_period = "10s"
    interval = "15s"
    timeout = "5s"
    type = "http"
    method = "GET"
    path = "/actuator/health"
