spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway?sslmode=require
    username: postgres
    password: cpnMnYwuAmMYtjWyOpQqsIndvGtzSFDk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080
