spring:
  datasource:
    url: jdbc:postgresql://trolley.proxy.rlwy.net:18984/railway?sslmode=require
    username: postgres
    password: cpnMnYwuAmMYtjWyOpQqsIndvGtzSFDk
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080
