spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway?sslmode=require
    username: postgres
    password: cpnMnYwuAmMYtjWyOpQqsIndvGtzSFDk
  jpa:
    show-sql: false               # Turn off Hibernate SQL logging
    properties:
      hibernate:
        format_sql: false          # SQL formatting off to reduce verbosity
    hibernate:
      ddl-auto: none               # Disable automatic schema updates (optional)
  sql:
    init:
      mode: always                 # Keep if you want initialization scripts to run

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: ERROR        # Hide all Hibernate SQL logs
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR  # Hide parameter binding logs
