spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: your_super_secret_key_here
  expiration-ms: 86400000  # 1 day in milliseconds
